import { StyleSheet } from 'react-native';
import { Spacing, Radius, LightColors } from '../../constants/theme';

export const createStyles = (colors: typeof LightColors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.bg.primary },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.bg.primary },
    loadingText: { marginTop: 12, fontSize: 14, color: colors.text.secondary, fontWeight: '600' },
    tabRow: { flexDirection: 'row', backgroundColor: colors.bg.secondary, borderBottomWidth: 1, borderBottomColor: colors.border },
    tabButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, gap: 6, borderBottomWidth: 3, borderBottomColor: 'transparent' },
    tabText: { fontSize: 12, fontWeight: '600', color: colors.text.secondary },
    scrollContent: { padding: Spacing.lg },
    tabContent: { gap: 16 },
    sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
    sectionTitle: { fontSize: 15, fontWeight: '800', color: colors.text.primary },
    outlineBtn: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: colors.primary, borderRadius: Radius.md, paddingHorizontal: 12, paddingVertical: 6, gap: 4 },
    outlineBtnText: { color: colors.primary, fontSize: 11, fontWeight: '700' },
    primaryBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, borderRadius: Radius.md, paddingHorizontal: 12, paddingVertical: 6, gap: 4 },
    primaryBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
    card: { backgroundColor: colors.bg.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: colors.border, padding: Spacing.lg },
    cardTitle: { fontSize: 13, fontWeight: '800', color: colors.text.primary, marginBottom: 12 },
    cardSubTitle: { fontSize: 12, fontWeight: '700', color: colors.text.secondary, marginBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.border, paddingBottom: 4 },
    materialRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.border },
    rmName: { fontSize: 13, fontWeight: '700', color: colors.text.primary },
    rmSku: { fontSize: 10, color: colors.text.muted, marginTop: 2 },
    rmStock: { fontSize: 13, fontWeight: '600', color: colors.text.primary },
    rmMin: { fontSize: 10, color: colors.text.muted, marginTop: 2 },
    batchRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border },
    batchRmName: { fontSize: 13, fontWeight: '700', color: colors.text.primary },
    batchNoLabel: { fontSize: 11, color: colors.text.secondary, marginTop: 2 },
    batchExpLabel: { fontSize: 10, color: colors.danger, marginTop: 2 },
    batchStock: { fontSize: 13, fontWeight: '600', color: colors.text.primary },
    batchRate: { fontSize: 10, color: colors.text.muted, marginTop: 2 },
    voidBtn: { padding: 6, marginLeft: 12 },
    emptyText: { fontSize: 12.5, color: colors.text.muted, fontStyle: 'italic', textAlign: 'center', paddingVertical: 20 },
    emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, gap: 12 },
    recipeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', borderBottomWidth: 1, borderBottomColor: colors.border, paddingBottom: 10, marginBottom: 10 },
    recipeTitle: { fontSize: 14, fontWeight: '800', color: colors.text.primary },
    recipeYield: { fontSize: 11, color: colors.text.muted, marginTop: 2 },
    deleteRecipeBtn: { padding: 6 },
    ingredientsList: { gap: 6 },
    ingredientsHeaderLabel: { fontSize: 11, fontWeight: '700', color: colors.text.secondary, marginBottom: 4 },
    ingredientItem: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
    ingredientName: { fontSize: 12, color: colors.text.primary },
    ingredientQty: { fontSize: 12, fontWeight: '600', color: colors.text.primary },
    batchCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border, paddingBottom: 10, marginBottom: 10 },
    batchTitle: { fontSize: 14, fontWeight: '800', color: colors.text.primary },
    batchSubNo: { fontSize: 11, color: colors.text.muted, marginTop: 2 },
    statusBadge: { borderWidth: 1, borderRadius: 4, paddingHorizontal: 8, paddingVertical: 2 },
    statusBadgeText: { fontSize: 9, fontWeight: '800' },
    batchMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginBottom: 12 },
    metaLabel: { fontSize: 11.5, color: colors.text.secondary },
    metaVal: { fontWeight: '700', color: colors.text.primary },
    batchIngredientsConsumedSection: { backgroundColor: colors.bg.secondary, borderRadius: Radius.md, padding: 10, borderWidth: 1, borderColor: colors.border, gap: 4, marginBottom: 12 },
    consumedIngItem: { fontSize: 11, color: colors.text.secondary },
    qcBox: { backgroundColor: colors.success + '0a', borderColor: colors.success + '20', borderWidth: 1, borderRadius: Radius.md, padding: 10, gap: 2, marginBottom: 8 },
    qcBoxTitle: { fontSize: 11, fontWeight: '700', color: colors.success },
    qcBoxText: { fontSize: 11, color: colors.text.secondary },
    batchActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 4 },
    cancelBatchBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: colors.danger + '30', borderRadius: Radius.sm, paddingHorizontal: 10, paddingVertical: 5 },
    cancelBatchBtnText: { color: colors.danger, fontSize: 11, fontWeight: '700' },
    completeBatchBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.success, borderRadius: Radius.sm, paddingHorizontal: 10, paddingVertical: 5 },
    completeBatchBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
    modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    modalBackdrop: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)' },
    modalContainer: { width: '90%', maxWidth: 520, maxHeight: '90%', backgroundColor: colors.bg.card, borderRadius: Radius.lg, borderWidth: 1, borderColor: colors.border, overflow: 'hidden', elevation: 20 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: Spacing.lg, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.bg.secondary },
    modalTitle: { fontSize: 15, fontWeight: '800', color: colors.text.primary },
    modalError: { backgroundColor: colors.danger + '10', borderColor: colors.danger + '35', borderWidth: 1, color: colors.danger, fontSize: 12, fontWeight: '600', padding: 10, marginHorizontal: Spacing.lg, marginTop: Spacing.md, borderRadius: Radius.sm },
    modalForm: { padding: Spacing.lg },
    inputLabel: { fontSize: 11, fontWeight: '700', color: colors.text.secondary, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
    input: { backgroundColor: colors.bg.primary, borderWidth: 1, borderColor: colors.border, borderRadius: Radius.md, paddingHorizontal: 12, paddingVertical: 10, fontSize: 13, color: colors.text.primary, marginBottom: 16 },
    pickerWrapper: { borderWidth: 1, borderColor: colors.border, borderRadius: Radius.md, backgroundColor: colors.bg.primary, marginBottom: 16, height: 40, justifyContent: 'center' },
    formIngredientsTitle: { fontSize: 12, fontWeight: '800', color: colors.text.primary, marginTop: 8, marginBottom: 12 },
    bomIngredientInputRow: { flexDirection: 'row', gap: 10, marginBottom: 10, alignItems: 'center' },
    removeRowBtn: { padding: 4 },
    addIngredientRowBtn: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 4, paddingVertical: 6, paddingHorizontal: 10, borderWidth: 1, borderColor: colors.primary + '30', borderRadius: Radius.sm, marginTop: 4, marginBottom: 16 },
    addIngredientRowBtnText: { color: colors.primary, fontSize: 11, fontWeight: '700' },
    warningDisclaimer: { fontSize: 11, color: colors.text.muted, lineHeight: 14, backgroundColor: colors.bg.secondary, padding: 10, borderRadius: Radius.sm, borderWidth: 1, borderColor: colors.border, marginBottom: 16 },
    modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, padding: Spacing.lg, borderTopWidth: 1, borderTopColor: colors.border },
    cancelBtn: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: Radius.md, borderWidth: 1, borderColor: colors.border },
    cancelBtnText: { fontSize: 13, color: colors.text.secondary, fontWeight: '600' },
    submitBtn: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: Radius.md, backgroundColor: colors.primary },
    submitBtnText: { fontSize: 13, color: '#fff', fontWeight: '700' },
  });
