const PHARMACOPOEIA_SEED_DATA = [
  // ── 1. HERBAL DRAVYAS (Plant Source) ──────────────────────────────────
  {
    ayurvedicName: 'ASHWAGANDHA',
    botanicalName: 'Withania somnifera (L.) Dunal',
    family: 'Solanaceae',
    partUsed: 'Root',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 15',
    synonyms: ['Asgandh', 'Indian Ginseng', 'Winter Cherry', 'Withania', 'Hayahvaya'],
    therapeuticUses: ['Rasayana', 'Balya', 'Brimhana', 'Vatapittashamana', 'Nidrajanana'],
    rasa: ['Tikta', 'Kashaya'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Laghu', 'Snigdha'],
    dosage: '3 - 6 g of root powder per day',
    description: 'Dried mature roots of Withania somnifera, widely used in Ayurveda for adaptogenic, restorative, and nervine strengthening actions.'
  },
  {
    ayurvedicName: 'TULSI',
    botanicalName: 'Ocimum sanctum L. (Ocimum tenuiflorum L.)',
    family: 'Lamiaceae',
    partUsed: 'Leaf',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 117',
    synonyms: ['Surasa', 'Holy Basil', 'Vrinda', 'Devadundubhi'],
    therapeuticUses: ['Kaphapatta-hara', 'Kasahara', 'Shvasahara', 'Jwarahara', 'Krimighna'],
    rasa: ['Katu', 'Tikta'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '2 - 3 ml leaf juice or 1 - 3 g leaf powder',
    description: 'Dried or fresh leaves of Ocimum sanctum, esteemed for respiratory support, immunomodulatory, and antimicrobial properties.'
  },
  {
    ayurvedicName: 'SHATAVARI',
    botanicalName: 'Asparagus racemosus Willd.',
    family: 'Liliaceae / Asparagaceae',
    partUsed: 'Tuberous Root',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol IV, pg 108',
    synonyms: ['Satavari', 'Shatamull', 'Wild Asparagus', 'Abhiru'],
    therapeuticUses: ['Stanyajanana', 'Rasayana', 'Balya', 'Vatapitta-hara', 'Shukrajanana'],
    rasa: ['Madhura', 'Tikta'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha'],
    dosage: '3 - 6 g powder per day',
    description: 'Tuberous roots of Asparagus racemosus, highly valued for female reproductive health, galactagogue, and cooling Rasayana effects.'
  },
  {
    ayurvedicName: 'GUDUCHI',
    botanicalName: 'Tinospora cordifolia (Willd.) Miers',
    family: 'Menispermaceae',
    partUsed: 'Stem',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 41',
    synonyms: ['Giloy', 'Gilo', 'Amrita', 'Chinnaruha', 'Heart-leaved Moonseed'],
    therapeuticUses: ['Jwarahara', 'Dahaprashamana', 'Rasayana', 'Tridoshashamaka', 'Pramehahara'],
    rasa: ['Tikta', 'Kashaya'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha'],
    dosage: '3 - 6 g powder or 10 - 20 ml stem juice',
    description: 'Dried mature stems of Tinospora cordifolia, one of the foremost immunomodulators, anti-pyretic and hepatoprotective herbs in API.'
  },
  {
    ayurvedicName: 'AMALAKI',
    botanicalName: 'Phyllanthus emblica L. (Emblica officinalis Gaertn.)',
    family: 'Euphorbiaceae / Phyllanthaceae',
    partUsed: 'Fresh/Dry Fruit',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 5',
    synonyms: ['Amla', 'Indian Gooseberry', 'Dhatri', 'Vayastha'],
    therapeuticUses: ['Rasayana', 'Chakshushya', 'Dahaprashamana', 'Pittahara', 'Vayasthapana'],
    rasa: ['Amla', 'Kashaya', 'Madhura', 'Tikta', 'Katu'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Guru', 'Ruksha', 'Sheeta'],
    dosage: '3 - 6 g fruit powder per day',
    description: 'Pericarp of dried or fresh mature fruits of Phyllanthus emblica, richest natural source of vitamin C complex and supreme Antioxidant Rasayana.'
  },
  {
    ayurvedicName: 'HARITAKI',
    botanicalName: 'Terminalia chebula Retz.',
    family: 'Combretaceae',
    partUsed: 'Fruit Pericarp',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 47',
    synonyms: ['Harad', 'Harde', 'Chebulic Myrobalan', 'Abhaya', 'Pathya'],
    therapeuticUses: ['Anulomana', 'Tridoshahara', 'Rasayana', 'Deepana', 'Pachana'],
    rasa: ['Kashaya', 'Tikta', 'Katu', 'Madhura', 'Amla'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 g powder per day',
    description: 'Dried fruit pericarp of Terminalia chebula, king of medicines in Ayurveda, known for mild laxative, digestive, and rejuvenating actions.'
  },
  {
    ayurvedicName: 'BIBHITAKI',
    botanicalName: 'Terminalia bellirica (Gaertn.) Roxb.',
    family: 'Combretaceae',
    partUsed: 'Fruit Pericarp',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 26',
    synonyms: ['Baheda', 'Beleric Myrobalan', 'Aksha', 'Vibhida'],
    therapeuticUses: ['Kaphapittahara', 'Bhedana', 'Kasahara', 'Chakshushya', 'Keshya'],
    rasa: ['Kashaya'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Ruksha'],
    dosage: '3 - 6 g pericarp powder per day',
    description: 'Dried mature fruit pericarp of Terminalia bellirica, essential component of Triphala formulation, effective for cough and throat disorders.'
  },
  {
    ayurvedicName: 'YASHTIMADHU',
    botanicalName: 'Glycyrrhiza glabra L.',
    family: 'Fabaceae',
    partUsed: 'Root/Rhizome',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 127',
    synonyms: ['Mulethi', 'Licorice', 'Sweetwood', 'Klitaka'],
    therapeuticUses: ['Kanthya', 'Kasahara', 'Vranaropana', 'Pittahara', 'Chakshushya'],
    rasa: ['Madhura'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha'],
    dosage: '1 - 3 g powder per day',
    description: 'Dried roots and stolons of Glycyrrhiza glabra, soothing demulcent for sore throat, hyperacidity, and mucosal healing.'
  },
  {
    ayurvedicName: 'PIPPALI',
    botanicalName: 'Piper longum L.',
    family: 'Piperaceae',
    partUsed: 'Fruit',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 91',
    synonyms: ['Long Pepper', 'Magadhi', 'Kana', 'Vaidehi'],
    therapeuticUses: ['Deepana', 'Pachana', 'Kasahara', 'Shvasahara', 'Rasayana'],
    rasa: ['Katu'],
    virya: 'Anushnasheeta',
    vipaka: 'Madhura',
    guna: ['Laghu', 'Snigdha', 'Tikshna'],
    dosage: '0.5 - 1 g powder per day',
    description: 'Dried spikes of Piper longum, potent bioavailability enhancer (Yogavahi), bio-enhancer and respiratory stimulant.'
  },
  {
    ayurvedicName: 'MARICHA',
    botanicalName: 'Piper nigrum L.',
    family: 'Piperaceae',
    partUsed: 'Fruit',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 77',
    synonyms: ['Kali Mirch', 'Black Pepper', 'Vellaja', 'Kolu'],
    therapeuticUses: ['Deepana', 'Pachana', 'Kaphavata-hara', 'Krimighna', 'Shoolaprashamana'],
    rasa: ['Katu'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Tikshna'],
    dosage: '0.5 - 1 g powder per day',
    description: 'Dried mature fruits of Piper nigrum, classic carminative and piperine source.'
  },
  {
    ayurvedicName: 'SHUNTHI',
    botanicalName: 'Zingiber officinale Rosc.',
    family: 'Zingiberaceae',
    partUsed: 'Dry Rhizome',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 103',
    synonyms: ['Sonth', 'Dry Ginger', 'Nagara', 'Mhashadha'],
    therapeuticUses: ['Deepana', 'Pachana', 'Vata-kaphahara', 'Amavata-hara', 'Vamana-hara'],
    rasa: ['Katu'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Laghu', 'Snigdha'],
    dosage: '1 - 2 g powder per day',
    description: 'Dried rhizome of Zingiber officinale, supreme digestive stimulant and anti-inflammatory.'
  },
  {
    ayurvedicName: 'GUGGULU',
    botanicalName: 'Commiphora wightii (Arn.) Bhandari',
    family: 'Burseraceae',
    partUsed: 'Exudate/Resin',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 43',
    synonyms: ['Guggul', 'Indian Bdellium', 'Devadhupa', 'Purified Resin'],
    therapeuticUses: ['Medohara', 'Vatarakta-hara', 'Amavata-hara', 'Sthoulyahara', 'Bhangaropana'],
    rasa: ['Tikta', 'Katu', 'Kashaya', 'Madhura'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha', 'Tikshna', 'Sukshma'],
    dosage: '2 - 4 g purified resin per day',
    description: 'Oleogum resin of Commiphora wightii, renowned hypolipidemic, anti-arthritic, and weight management gum resin.'
  },
  {
    ayurvedicName: 'HARIDRA',
    botanicalName: 'Curcuma longa L.',
    family: 'Zingiberaceae',
    partUsed: 'Rhizome',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 45',
    synonyms: ['Haldi', 'Turmeric', 'Nisha', 'Kanchani'],
    therapeuticUses: ['Kushthaghna', 'Krimighna', 'Vranaropana', 'Kandughna', 'Pramehahara'],
    rasa: ['Tikta', 'Katu'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Ruksha', 'Laghu'],
    dosage: '1 - 3 g rhizome powder per day',
    description: 'Dried rhizomes of Curcuma longa, natural curcumin source for anti-inflammatory and skin health applications.'
  },
  {
    ayurvedicName: 'MANJISTHA',
    botanicalName: 'Rubia cordifolia L.',
    family: 'Rubiaceae',
    partUsed: 'Stem/Root',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol III, pg 112',
    synonyms: ['Indian Madder', 'Aruna', 'Raktanga'],
    therapeuticUses: ['Raktashodhaka', 'Kushthaghna', 'Vranaropana', 'Pittahara'],
    rasa: ['Tikta', 'Kashaya', 'Madhura'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Guru', 'Ruksha'],
    dosage: '1 - 3 g powder per day',
    description: 'Dried stems and roots of Rubia cordifolia, premier Ayurvedic blood purifier and complexion enhancer.'
  },
  {
    ayurvedicName: 'BHRINGRAJ',
    botanicalName: 'Eclipta alba (L.) Hassk.',
    family: 'Asteraceae',
    partUsed: 'Whole Plant',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol II, pg 21',
    synonyms: ['False Daisy', 'Keshraja', 'Markava'],
    therapeuticUses: ['Keshya', 'Yakrid-uttejaka', 'Rasayana', 'Shirorogahara'],
    rasa: ['Katu', 'Tikta'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 ml juice or 1 - 3 g powder',
    description: 'Whole plant of Eclipta alba, celebrated hair tonic (Keshya) and liver stimulant.'
  },
  {
    ayurvedicName: 'ARJUNA',
    botanicalName: 'Terminalia arjuna (Roxb. ex DC.) Wight & Arn.',
    family: 'Combretaceae',
    partUsed: 'Stem Bark',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol II, pg 11',
    synonyms: ['Arjun Bark', 'Kukubha', 'Partha'],
    therapeuticUses: ['Hridya', 'Raktastambhana', 'Kshayahara', 'Vranaropana'],
    rasa: ['Kashaya'],
    virya: 'Sheeta',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 g bark powder per day',
    description: 'Stem bark of Terminalia arjuna, premier Ayurvedic cardiotonic (Hridya) and vascular tonic.'
  },
  {
    ayurvedicName: 'JATAMANSI',
    botanicalName: 'Nardostachys jatamansi DC.',
    family: 'Valerianaceae',
    partUsed: 'Rhizome/Root',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol II, pg 51',
    synonyms: ['Spikenard', 'Tapaswini', 'Kanchana'],
    therapeuticUses: ['Nidrajanana', 'Manasadoshahara', 'Shirorogahara', 'Hridya'],
    rasa: ['Tikta', 'Kashaya', 'Madhura'],
    virya: 'Sheeta',
    vipaka: 'Katu',
    guna: ['Laghu', 'Snigdha'],
    dosage: '1 - 3 g rhizome powder per day',
    description: 'Dried rhizome of Nardostachys jatamansi, renowned calmative, anti-anxiety and sedative herb.'
  },
  {
    ayurvedicName: 'SHALLAKI',
    botanicalName: 'Boswellia serrata Roxb.',
    family: 'Burseraceae',
    partUsed: 'Gum Resin',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol IV, pg 114',
    synonyms: ['Indian Frankincense', 'Boswellia', 'Gajabhakshya'],
    therapeuticUses: ['Sandhivata-hara', 'Amavata-hara', 'Vranaropana', 'Shoolaprashamana'],
    rasa: ['Kashaya', 'Tikta', 'Madhura'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '1 - 3 g gum resin per day',
    description: 'Gum resin of Boswellia serrata, source of boswellic acids for joint flexibility and cartilage support.'
  },

  // ── 2. RASA / MINERAL DRAVYAS (Metals, Minerals & Bhasma Raw Materials) ──
  {
    ayurvedicName: 'SHILAJIT',
    botanicalName: 'Asphaltum punjabianum (Mineral Pitch)',
    family: 'Mineral Resin Exudate',
    partUsed: 'Purified Exudate (Shodhita)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 101',
    synonyms: ['Mineral Pitch', 'Black Bitumen', 'Girija', 'Silajitu'],
    therapeuticUses: ['Rasayana', 'Balya', 'Pramehahara', 'Vrishya', 'Yogavahi'],
    rasa: ['Tikta', 'Katu', 'Kashaya'],
    virya: 'Anushnasheeta',
    vipaka: 'Katu',
    guna: ['Guru', 'Ruksha'],
    dosage: '250 - 500 mg purified resin per day',
    description: 'Natural mineral pitch exuded from Himalayan rocks, potent Rasayana for stamina and cellular energy.'
  },
  {
    ayurvedicName: 'SWARNA (GOLD)',
    botanicalName: 'Aurum (Pure Gold Metal)',
    family: 'Elemental Metal',
    partUsed: 'Purified Leaf/Foil (Shodhita)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol VII, Monograph 12 (Minerals & Metals)',
    synonyms: ['Kanaka', 'Gold Metal', 'Haema', 'Hiranya'],
    therapeuticUses: ['Medhya', 'Rasayana', 'Ojovardhaka', 'Vrishya', 'Visha-hara'],
    rasa: ['Madhura', 'Kashaya'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha'],
    dosage: '15.5 - 31.25 mg Bhasma per day',
    description: 'Elemental Gold subjected to Shodhana and Marana to prepare Swarna Bhasma for memory, immunity, and longevity.'
  },
  {
    ayurvedicName: 'ABHRAKA (MICA)',
    botanicalName: 'Biotite Mica Ore',
    family: 'Mineral Silicate',
    partUsed: 'Purified Ore (Shodhita Black Mica)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol VII, Monograph 1 (Minerals & Metals)',
    synonyms: ['Biotite Mica', 'Gagana', 'Girija'],
    therapeuticUses: ['Rasayana', 'Kasahara', 'Shvasahara', 'Kshayahara', 'Balya'],
    rasa: ['Madhura'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Snigdha'],
    dosage: '125 - 250 mg Bhasma per day',
    description: 'Purified Black Biotite Mica processed through multi-puta calcination to prepare Abhraka Bhasma.'
  },
  {
    ayurvedicName: 'GANDHAKA (SULFUR)',
    botanicalName: 'Elemental Sulfur Ore',
    family: 'Mineral Element',
    partUsed: 'Purified Sulfur (Shodhita)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol VII, Monograph 5 (Minerals & Metals)',
    synonyms: ['Shulvari', 'Brimstone', 'Sulfur'],
    therapeuticUses: ['Kushthaghna', 'Krimighna', 'Rasayana', 'Kandughna'],
    rasa: ['Katu', 'Tikta', 'Kashaya'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Snigdha'],
    dosage: '125 - 250 mg Shodhita Gandhaka per day',
    description: 'Elemental Sulfur purified in cow milk/ghee (Shodhana) used in Kampi and Rasayana formulations.'
  },

  // ── 3. ANIMAL DRAVYAS (Jantava Dravyas) ──────────────────────────────
  {
    ayurvedicName: 'MADHU (HONEY)',
    botanicalName: 'Apis mellifera Exudate',
    family: 'Insect Product',
    partUsed: 'Honey (Madhu)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol III, pg 95',
    synonyms: ['Honey', 'Makshika', 'Kshaudra'],
    therapeuticUses: ['Yogavahi', 'Kaphahara', 'Chedana', 'Vranaropana', 'Lekhana'],
    rasa: ['Madhura', 'Kashaya'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Laghu', 'Ruksha'],
    dosage: '5 - 10 ml as Anupana or medium',
    description: 'Pure natural honey, supreme bio-vehicle (Yogavahi) and natural demulcent.'
  },
  {
    ayurvedicName: 'SHANKHA (CONCH SHELL)',
    botanicalName: 'Turbinella pyrum Shell',
    family: 'Mollusca Shell',
    partUsed: 'Purified Calcined Shell (Shodhita Shankha)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol VII, Monograph 18 (Minerals & Animal Origin)',
    synonyms: ['Conch Shell', 'Kambu', 'Shankha Bhasma Source'],
    therapeuticUses: ['Amlapitta-hara', 'Shoolaprashamana', 'Grahani-hara', 'Deepana'],
    rasa: ['Katu'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '250 - 500 mg Bhasma per day',
    description: 'Marine conch shell calcined into Shankha Bhasma for hyperacidity, duodenal ulcers, and abdominal colic.'
  },

  // ── 4. SCHEDULE E1 TOXIC HERBAL DRAVYAS (Requiring Mandatory Shodhana) ─
  {
    ayurvedicName: 'VATSANABHA',
    botanicalName: 'Aconitum ferox Wall. ex Ser.',
    family: 'Ranunculaceae',
    partUsed: 'Purified Root (Shodhita Vatsanabha)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 123 (Schedule E1 Item)',
    synonyms: ['Monkshood', 'Indian Aconite', 'Amrita', 'Visha'],
    therapeuticUses: ['Jwarahara', 'Vatashoolahara', 'Sannipatajwarahara', 'Yogavahi'],
    rasa: ['Madhura'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Laghu', 'Ruksha', 'Tikshna', 'Vyavayi', 'Vikasi'],
    dosage: '15 - 30 mg Shodhita root powder per day under strict supervision',
    description: 'Schedule E1 toxic root of Aconitum ferox, requires mandatory Gomutra/Godugdha Shodhana prior to formulation.'
  },
  {
    ayurvedicName: 'BHALLATAKA',
    botanicalName: 'Semecarpus anacardium L.f.',
    family: 'Anacardiaceae',
    partUsed: 'Purified Fruit (Shodhita Fruit)',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol II, pg 19 (Schedule E1 Item)',
    synonyms: ['Marking Nut', 'Arushkara', 'Agnimukha'],
    therapeuticUses: ['Kushthaghna', 'Arshoghna', 'Vata-hara', 'Kapha-hara', 'Rasayana'],
    rasa: ['Katu', 'Tikta', 'Kashaya'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha', 'Tikshna'],
    dosage: '1 - 2 g Shodhita fruit per day',
    description: 'Schedule E1 toxic Marking Nut of Semecarpus anacardium, purified in Brick Powder/Cow Milk before medicinal use.'
  },
  {
    ayurvedicName: 'DHATAKI',
    botanicalName: 'Woodfordia fruticosa (L.) Kurz',
    family: 'Lythraceae',
    partUsed: 'Flower',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 32',
    synonyms: ['Dhataki Pushpa', 'Dhatri Pushpa', 'Fire Flame Bush', 'Woodfordia', 'Dhatki'],
    therapeuticUses: ['Sandhanakara', 'Atisarahara', 'Raktapittahara', 'Vranaropana', 'Kasahara'],
    rasa: ['Kashaya'],
    virya: 'Sheeta',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 g flower powder per day',
    description: 'Dried flowers of Woodfordia fruticosa, vital natural yeast fermentation catalyst for all Asava and Arishta Ayurvedic preparations.'
  },
  {
    ayurvedicName: 'DRAKSHA',
    botanicalName: 'Vitis vinifera L.',
    family: 'Vitaceae',
    partUsed: 'Dry Fruit',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 35',
    synonyms: ['Munakka', 'Raisin', 'Kishmish', 'Grapes', 'Gostani'],
    therapeuticUses: ['Brimhana', 'Vatapittashamana', 'Kasahara', 'Tarpana', 'Chakshushya'],
    rasa: ['Madhura'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha'],
    dosage: '10 - 20 g dry fruit per day',
    description: 'Dried mature fruits of Vitis vinifera, sweet restorative used in Draksharishta, Chyawanprash, and cooling Rasayana tonics.'
  },
  {
    ayurvedicName: 'MUSTA',
    botanicalName: 'Cyperus rotundus L.',
    family: 'Cyperaceae',
    partUsed: 'Rhizome/Tuber',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol III, pg 129',
    synonyms: ['Nagarmotha', 'Nut Grass', 'Mustaka', 'Gundra'],
    therapeuticUses: ['Deepana', 'Pachana', 'Grahi', 'Jwarahara', 'Kaphapittahara'],
    rasa: ['Tikta', 'Katu', 'Kashaya'],
    virya: 'Sheeta',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 g rhizome powder per day',
    description: 'Dried rhizome of Cyperus rotundus, supreme digestive, anti-diarrheal, anti-pyretic and carminative herb in API.'
  },
  {
    ayurvedicName: 'KATUKA',
    botanicalName: 'Picrorhiza kurroa Royle ex Benth.',
    family: 'Scrophulariaceae',
    partUsed: 'Rhizome/Root',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol II, pg 85',
    synonyms: ['Kutki', 'Kutaki', 'Picrorhiza', 'Tiktaka'],
    therapeuticUses: ['Bhedana', 'Jwarahara', 'Yakrid विकार (Hepatoprotective)', 'Pittavirechana', 'Deepana'],
    rasa: ['Tikta'],
    virya: 'Sheeta',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '1 - 3 g rhizome powder per day',
    description: 'Dried rhizomes of Picrorhiza kurroa, master bitter cholagogue, hepatoprotective, and liver detoxifier.'
  },
  {
    ayurvedicName: 'TIL OIL',
    botanicalName: 'Sesamum indicum L.',
    family: 'Pedaliaceae',
    partUsed: 'Seed Oil',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 115',
    synonyms: ['Tila Taila', 'Til Tail', 'Sesame Oil', 'Gingelly Oil'],
    therapeuticUses: ['Vatashamana', 'Balya', 'Tarpana', 'Tvachya', 'Snehana'],
    rasa: ['Madhura', 'Kashaya', 'Tikta'],
    virya: 'Ushna',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha', 'Sukshma', 'Vyavayi'],
    dosage: '10 - 20 ml per day or base for medicated tailas',
    description: 'Pure expressed oil from seeds of Sesamum indicum, primary base oil (Taila Kalpana) for all Ayurvedic medicated oils.'
  },
  {
    ayurvedicName: 'MAIDA LAKDI',
    botanicalName: 'Litsea glutinosa (Lour.) C.B.Rob.',
    family: 'Lauraceae',
    partUsed: 'Stem Bark',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol V, pg 112',
    synonyms: ['Maida Lakri', 'Meda Lakdi', 'Medasaka', 'Litsea glutinosa', 'Maida Lakda'],
    therapeuticUses: ['Vatashamana', 'Shoolahara', 'Vranaropana', 'Deepana', 'Kapha-Vata-hara'],
    rasa: ['Katu', 'Tikta', 'Kashaya'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Snigdha'],
    dosage: '1 - 3 g bark powder per day',
    description: 'Dried stem bark of Litsea glutinosa, renowned mucilaginous analgesic, Vata-pacifying, and wound-healing bark in API.'
  },
  {
    ayurvedicName: 'MAHUA',
    botanicalName: 'Madhuca longifolia (J.Koenig ex L.) J.F.Macbr.',
    family: 'Sapotaceae',
    partUsed: 'Flower',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 102',
    synonyms: ['Madhuka', 'Madhuka Pushpa', 'Mahua Flower', 'Mahwa', 'Butter Tree', 'Honey Tree', 'Gudapushpa'],
    therapeuticUses: ['Rasayana', 'Balya', 'Brimhana', 'Vatapittashamana', 'Sandhanakara'],
    rasa: ['Madhura'],
    virya: 'Sheeta',
    vipaka: 'Madhura',
    guna: ['Guru', 'Snigdha'],
    dosage: '10 - 15 g flower or 3 - 6 g powder per day',
    description: 'Dried flowers of Madhuca longifolia, rich in natural fermented sugars, vital yeast substrate (Gudapushpa) for Asavas/Arishtas and nutritive Rasayana.'
  },
  {
    ayurvedicName: 'VARUNA',
    botanicalName: 'Crateva nurvala Buch.-Ham.',
    family: 'Capparaceae',
    partUsed: 'Stem Bark',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 120',
    synonyms: ['Varun', 'Crataeva', 'Three Leaved Caper', 'Setu', 'Tiktashaka'],
    therapeuticUses: ['Ashmarihara', 'Mutrakrichrahara', 'Gulmahara', 'Deepana', 'Vata-Kapha-hara'],
    rasa: ['Tikta', 'Kashaya'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 g bark powder per day',
    description: 'Dried stem bark of Crateva nurvala, master lithontriptic (Ashmarihara) for renal calculi, prostate enlargement, and urinary tract health.'
  },
  {
    ayurvedicName: 'KANKOLA',
    botanicalName: 'Piper cubeba L.f.',
    family: 'Piperaceae',
    partUsed: 'Fruit',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol I, pg 58',
    synonyms: ['Kankol', 'Cubeb Pepper', 'Tailpepper', 'Sugandhamuricha'],
    therapeuticUses: ['Deepana', 'Pachana', 'Mutrakrichrahara', 'Kanthya', 'Mukharogahara'],
    rasa: ['Katu', 'Tikta'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Tikshna'],
    dosage: '1 - 2 g fruit powder per day',
    description: 'Dried fruits of Piper cubeba, aromatic spice and urinary antiseptic used in classic Ayurvedic formulations.'
  },
  {
    ayurvedicName: 'USHEERA',
    botanicalName: 'Vetiveria zizanioides (L.) Nash',
    family: 'Poaceae',
    partUsed: 'Root',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol III, pg 219',
    synonyms: ['Khas', 'Khas Khas', 'Vetiver', 'Ushir', 'Vira', 'Sugandhimula'],
    therapeuticUses: ['Dahaprashamana', 'Pittahara', 'Trishnahara', 'Jwarahara', 'Svedapanayana'],
    rasa: ['Tikta', 'Madhura'],
    virya: 'Sheeta',
    vipaka: 'Katu',
    guna: ['Laghu', 'Ruksha'],
    dosage: '3 - 6 g root powder / decoction per day',
    description: 'Dried fibrous roots of Vetiveria zizanioides, renowned cooling aromatic root for Pitta soothing, fevers, and thirst relief.'
  },
  {
    ayurvedicName: 'TALISPATRA',
    botanicalName: 'Abies webbiana Lindl.',
    family: 'Pinaceae',
    partUsed: 'Leaf',
    pharmacopoeialStandard: 'API',
    monographRef: 'API Part I, Vol IV, pg 119',
    synonyms: ['Talis', 'Talispatri', 'Himalayan Silver Fir', 'Patradhya'],
    therapeuticUses: ['Kasahara', 'Shvasahara', 'Deepana', 'Kaphavata-hara', 'Ruchya'],
    rasa: ['Tikta', 'Katu'],
    virya: 'Ushna',
    vipaka: 'Katu',
    guna: ['Laghu', 'Tikshna'],
    dosage: '2 - 3 g leaf powder per day',
    description: 'Dried leaves of Abies webbiana, key ingredient in Talisadi Churna for bronchodilative and respiratory support.'
  }
];

module.exports = {
  PHARMACOPOEIA_SEED_DATA
};
